# Generated by Django 6.0.4 on 2026-04-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seats_filled', models.IntegerField(default=0)),
                ('total_seats', models.IntegerField()),
                ('status', models.CharField(default='DRAFT', max_length=20)),
            ],
        ),
    ]
